@startuml
left to right direction
actor Befragender as l
actor Beantwortender as s

package Beantwortung {
usecase "Umfrage beantworten" as UC5
usecase "Über E-Mail-Token einsteigen" as UC6
usecase "Formular ausfüllen" as UC7
usecase "Antwort abschicken" as UC8
}

package Befragung {
usecase "Umgrage erstellen" as UC1
usecase "Formular erstellen" as UC2
usecase "Adressdaten auswählen" as UC3
usecase "Umfrage aussenden" as UC4
}



s --> UC5
UC5 .. UC6 : <<include>>
UC5 .. UC7 : <<include>>
UC5 .. UC8 : <<include>>
l --> UC1
UC1 .. UC2 : <<include>>
UC1 .. UC3 : <<include>>
UC1 .. UC4 : <<include>>


@enduml