package at.htl.boundary;

import at.htl.model.Template;
import at.htl.repositories.TemplateRepository;
import org.eclipse.microprofile.openapi.annotations.Operation;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.TypedQuery;
import javax.transaction.Transactional;
import javax.ws.rs.*;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

@Path("/template")
public class TemplateService {

    @Inject
    TemplateRepository qr;

    @Inject
    EntityManager em;

    @GET
    @Operation(
            summary = "Get all Templates"
    )
    @Produces(MediaType.APPLICATION_JSON)
    public List<Template> getAllTemplates() {
        return qr.listAll();
    }

    @GET
    @Operation(
            summary = "Get a Template by ID"
    )
    @Path("/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    public Template getTemplateById(@PathParam("id") Long id) {
        return qr.findById(id);
    }

    @GET
    @Operation(
            summary = "Get Markdown Text of the Template"
    )
    @Path("/{id}/markdown")
    @Produces(MediaType.TEXT_PLAIN)
    public String getMarkdown(@PathParam("id") Long id) {
        return qr.findById(id).getMarkdown();
    }

    @GET
    @Operation(
            summary = "Get Markdown Text of the Template by Name of it"
    )
    @Path("/{name}/markdown/name")
    @Produces(MediaType.TEXT_PLAIN)
    public String getMarkdownByName(@PathParam("name") String name) {

        try {
            TypedQuery<Template> tq = em.createNamedQuery("Template.getTemplateByName", Template.class)
                    .setParameter("NAME", name);
            Template q = tq.getSingleResult();
            return q.getMarkdown();
        } catch (NoResultException e) {
            return "Cannot find Template \"" + name + "\"";
        }
    }

    @GET
    @Operation(
            summary = "Get Markdown Text of the Template by Name of it as HTML"
    )
    @Path("/{name}/markdown/name")
    @Produces(MediaType.TEXT_HTML)
    public String getMarkdownByNameAsHTML(@PathParam("name") String name) {

        try {
            TypedQuery<Template> tq = em.createNamedQuery("Template.getTemplateByName", Template.class)
                    .setParameter("NAME", name);
            Template q = tq.getSingleResult();
            return q.getMarkdown();
        } catch (NoResultException e) {
            return "Cannot find Template \"" + name + "\"";
        }
    }

    @GET
    @Operation(
            summary = "Get Fieldnames of Template"
    )
    @Path("/{id}/fieldnames-id")
    @Produces(MediaType.APPLICATION_JSON)
    public List<String> getFieldnames(@PathParam("id") Long id) {
        return qr.findById(id).getFieldNames();
    }

    @GET
    @Operation(
            summary = "Get Fieldnames of Template"
    )
    @Path("/{name}/fieldnames")
    @Produces(MediaType.APPLICATION_JSON)
    public List<List<String>> getFieldnamesByName(@PathParam("name") String name) {

        TypedQuery<Template> tq = em.createNamedQuery("Template.getTemplateByName", Template.class)
                .setParameter("NAME", name);
        List<Template> templates = tq.getResultList();
        List<List<String>> fieldnames = new ArrayList<>();

        templates.forEach(q -> fieldnames.add(q.getFieldNames()));

        return fieldnames;
    }

    @POST
    @Operation(
            summary = "Create a new Template",
            description = "Create a new Template. Don't pass an ID because it will be auto-generated by the Database."
    )
    @Transactional
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public Response create(Template template, @Context UriInfo info) {
        qr.merge(template);
        return Response.created(URI.create(info.getPath())).build();
    }

    @DELETE
    @Transactional
    @Operation(
            summary = "Delete a Template by ID"
    )
    @Path("/{id}/template-id")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public Response deleteById(@PathParam("id") long id) {
        try {
            Template q = qr.findById(id);
            qr.deleteById(id);
            return Response.status(200).header("Deleted", q.getName()).build();
        } catch (Exception e) {
            return Response.status(400).header("Reason", "Template mit id " + id + " existiert nicht").build();
        }

    }

}
